apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "argocd.internal.starktastic.net"
  dnsNames:
    - "argocd.internal.starktastic.net"
