global:
  storageClass: "nfs-pv"
auth:
  existingSecret: postgres-admin-secret
  secretKeys:
    adminPasswordKey: postgres-password
primary:
  persistence:
    enabled: true
    storageClass: "nfs-pv"
    size: 8Gi
  initContainers:
    - name: rm-postmaster-lock-file
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
      command:
        - sh
        - -c
        - |
          if [ -f /bitnami/postgresql/data/postmaster.pid ]; then
            echo "ðŸ§Ÿ Zombie Lock Found: Deleting postmaster.pid"
            rm -f /bitnami/postgresql/data/postmaster.pid
          fi
  podSecurityContext:
    fsGroup: 1001
    enabled: true
  containerSecurityContext:
    runAsUser: 1001
    enabled: true
volumePermissions:
  enabled: true
