---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin-secret
  namespace: databases
spec:
  encryptedData:
    postgres-password: AgDLwpocphJLqATOCMLgKtM+3esRCCIcID5bYQd4kkJhPsnzBJEvC1jJgCrFdeI7cuc9GUjYYsR+cC3Q9c7fCGw4RrYvoaAqvn+hvyl7AFda+zEbL12bJxhDp9gLfomtkXoBhPQxE0Aa4J3T/uD7AE3eBNSWgBWOkC3UiIzHyf3sQe7iy8w1HTfyz6AxaY5maspYNUAJfLcY1FRoGYF7LzCSWvKfjoLXfgMASQpW+A0avuVMU1nZJPE3PlwflhWTJk63rdQD+JugYUD5pZe/lyKbbC4hwea8T9yS5fMoBNRtBrdmtMSEp/t6lkqgF1UZkYWjEZj6+uplkhuEumkbRybE/sPmAIJmbivlNVOI7M+H8bA7o3vdQNABKVyVm/Fpx76rmPwdsKnWVoSFQn1qndTadjQWi2ZY60yJSlhz04efi6Rkciqvzter+vhAIoMjCMpEgI+N5D0uyHABD6CB38UAYmJ/KB1oZ52qy2TGE7l8nDCSJBKtFVN9fq2xel28z+UEmIHR6RamVXA47+5HzJdpqYM/SIcrCBgc983u5wPIqgQywlDSZX7VCkBvUz4EHk2F5U4QxzTPop9WlCNGNTfN4zJiglTVUsi793V0Qw3MPeuAVXxjbWTdUVmV6pg+FyqnKNxTWws+zlDAxlF7wzRsRPhQ+svPDPnsF90HcP4XZlU7lu1HoP326pd3R0D19j1iQfXxDD8BJPQ+3APuURDUYtXxew==
  template:
    metadata:
      name: postgres-admin-secret
      namespace: databases
