---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-admin-secret
  namespace: databases
spec:
  encryptedData:
    redis-password: AgAInuI0A1rm6xJ3TaXU94g1KxUzvoNqB8Fz0+TtBC6ZZ9ItoMInAqEh9VhXz+8gBGhASft34T7D7CgYnrk95iqb6HoRNv2fpETEfiZn6s2EUrheOeAPIJ5HkcH6RyH4NuSI+NFYRCHTOKq6kESXDhCWah7Mbhqi+bbDaP+mlCl2QYn3LqmV5rGCyysmzwk2sfa+zgITy4Rw9z7ZqiM9rRWRjg30D1PcwxwqrCgVrupn8yVMsrNujxuCeTLCsfz2O0UwnLjsoBnUB+ykM7JbprvKb4kTt5FmqEmGbGNQT8Egl6VEKe7jYDhp10288AgrjQNzJf2lkLdYV6AXgzENFtlOX6LBmCnXhVP2APMqvK45YzbhvH6Cw9j9qPJdETJfD2BWJ2J4sXU6qLNV1ND4MiDciElpcMB4PLWR+SLDYOmnBJmEAWzaY18uo4bcV5bkb7R4krx2EpKzSmGVAOeWzpVeBWaLEMmOT3xSty9m9yzMwx5S+7VxhhpGLsneC8Zhdng4dkf03/zeQFgmPyxxa8acxgS9hEP6nh9g/1L1FzahuHvUtVdbruCylg6oi36518LZ9AXRO+1+5rWEVeotetc55dipdXyXiYO+jLygvKzEn1JJehkiZuNcUMxzd72Yh/ToXDAhseXz1w+vIrWODkNc1OkwhH+fBdcwxdx0w6iWs3GaqM1J7ly3Ri32JD/Aga0QByNuz8YJzhzJ7Q9zNLzMCSgDGg==
  template:
    metadata:
      name: redis-admin-secret
      namespace: databases
