apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-system
  annotations:
    kube-vip.io/loadbalancerIPs: "10.9.8.90"
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: LoadBalancer
  loadBalancerIP: "10.9.8.90"
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-traefik-system
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: 8443
