---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-secret
  namespace: databases
spec:
  encryptedData:
    password: AgCEDP36ZYrctWhUwDgYgGj2XuakEIRSxnfIAyf0YKoX7fHOsYFTBk8OEqWYRL0o7ojYbJKAuvGnZPeoooq5DOG1zT9jRk56S7nBBQl4HKASxE3GTciBdPIXGvqMaF60XtKC4sjfiomIcXUXTG1SjLVyxZuVHffMzqedWOvVfGoCQbHMc3BbAmSeFf39kwOV2xW7/C7jup5XdaIMa3U+BladpNddOe/sgVvDIwvni/vDGBbRvRAyzhregQz8lRb9HIPilhzddd0BMmyzzzo2p6U3r+eHgcuBgCdfNGb9Xtc7pK53hDHWxdrepF9EPSHawqnmhOioMZxH2WOEQFec8HfhzBjImUE22GqCmMFJZp+lT6IUoycIFLYU44FpuB3ov63ZHxfVN7N338alLfg0tafF3IjP8UvDoFAS0BnEMYKS8nXze4RDM6KFuyhB4V/K+CcdZln4fTvZxoWtFtnYFYwkwZ3KgrWMlT0FlI9ElIpHdiCoFfvWyHMtgHtU0HkHWfw6Tn0PG/I5ZbIy3QrzvSkAzudgo+hTwkzAUAfKIp/qhNTNruyo6JAdvDEghdOkjcM6Ned3W+ty69DMwe5h4k8EzbAbJtHP1yAVo8rB8KmB2+bVhw83+IWksbY1/2HQscB6bFST5EuYhq39J+tlb0pA8weFp3WgxgDAE/lCEHXK/SK7UVenLJoov87vGij7wZRrxUU9GehpX//sjMSgxKEkkpQMHg==
  template:
    metadata:
      name: authentik-db-secret
      namespace: databases
