apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress-route
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.starktastic.net`) && (PathPrefix(`/if/admin`) || PathPrefix(`/api/v3/admin`))
      kind: Rule
      services:
        - name: authentik-server
          port: 80
      middlewares:
        - name: internal-ip-allowlist

    - match: Host(`auth.starktastic.net`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
  tls: {}
