apiVersion: v1
kind: Service
metadata:
  name: authentik-ldap-outpost
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-ldap-outpost
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: authentik-ldap-outpost
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: 3389
    - name: ldaps
      port: 636
      protocol: TCP
      targetPort: 6636
    - name: http-metrics
      port: 9300
      protocol: TCP
      targetPort: 9300

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-ldap-outpost
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-ldap-outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-ldap-outpost
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-ldap-outpost
    spec:
      containers:
        - name: ldap
          image: ghcr.io/goauthentik/ldap:2025.12.1
          ports:
            - containerPort: 3389
              name: ldap
            - containerPort: 6636
              name: ldaps
            - containerPort: 9300
              name: http-metrics
          envFrom:
            - secretRef:
                name: authentik-ldap-outpost-api
          livenessProbe:
            httpGet:
              path: /outpost.goauthentik.io/ping
              port: 9300
            initialDelaySeconds: 5
            periodSeconds: 10
