apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starktastic-net-cert
  namespace: traefik-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: starktastic-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.starktastic.net"
  dnsNames:
    - "starktastic.net"
    - "*.starktastic.net"
    - "*.internal.starktastic.net"
