apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: benplus-vip-cert
  namespace: traefik-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: benplus-vip-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.benplus.vip"
  dnsNames:
    - "benplus.vip"
    - "*.benplus.vip"
