apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-web
  namespace: media
spec:
  entryPoints:
    - websec-int
  routes:
    - match: Host(`qbittorrent.internal.starktastic.net`)
      kind: Rule
      services:
        - name: qbittorrent-webui
          port: 8080
      middlewares:
        - name: authentik-middleware
          namespace: authentik
  tls:
    secretName: starktastic-net-tls

