apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - websec-int
  routes:
    - match: Host(`prowlarr.internal.starktastic.net`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
      middlewares:
        - name: rate-limit-strong
          namespace: traefik-system
        - name: authentik-middleware
          namespace: authentik
  tls: {}
