apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-library-pv
  resources:
    requests:
      storage: 10Ti
