name: Format

on:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format all YAML, JSON and shell files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.{yaml,yml,json}
          no_commit: true

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v4.0.1

      - name: Run shfmt
        run: shfmt -i 2 -ci -s -w **/*.sh || true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "style: apply automatic formatting"
