name: Format

on:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format all YAML files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.{yaml,yml,json}
          no_commit: true

      - name: sh-checker
        uses: luizm/action-sh-checker@v0.10.0
        env:
          SHFMT_OPTS: -i 2 -ci -s -w

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "style: apply automatic formatting"
